import json,pathlib
base=pathlib.Path('docs/next-five-2026-09-10');p=json.loads((base/'review/reviewed-proposal.json').read_text())
lines=['# NexusPoint: five editions for approval','','**Proposed September 13–17, 2026. No new editions scheduled or deployed.**','','The owner approved removal of the one-percentage-point tie tolerance. All proposed games now use unrounded movements with only numerically equal results tied. Display rounding remains 0.1 percentage point and does not determine rank. A machine-precision allowance only absorbs binary subtraction noise.','','The same rule applies to private previews and the already scheduled September 11–12 games. September 7–10 retain their existing scoring versions so saved grades remain valid. Dates, event sets and approvals are unchanged.','','The source/timing repairs and remaining evidence limits in [the audit](audit-other/REVIEW.md) still apply. Its old one-point tie conclusions are superseded here. The early NYT endorsement publication times and earliest Glasnow disclosure remain bounded rather than precisely known; prices describe observed movement, not isolated causality.','','| Proposed day | Edition | Distinct ranks |','|---|---|---:|']
for e in p['editions']:lines.append(f"| {e['date']} | {e['topic']} | {len(e['tieGroups'])} |")
for e in p['editions']:
 lines+=['','## '+e['date']+' — '+e['topic'],'','| Rank | Headline | Unrounded move (percentage points shown to 3 decimals) |','|---:|---|---:|']
 cards={c['id']:c for c in e['cards']}
 for rank,group in enumerate(e['tieGroups'],1):
  for id in group:
   c=cards[id];v=c['measuredChangePercentagePoints'];v=0 if abs(v)<1e-12 else v;lines.append(f"| {rank}{' (tie)' if len(group)>1 else ''} | {c['title']} | {v:+.3f} |")
 lines+=['',f"[Exact study]({pathlib.Path(e['study']).resolve()})",'', '**Initial play order:** '+' → '.join(cards[i]['title'] for i in e['initialOrder'])+'.']
lines+=['','Four proposed editions now have five distinct ranks. Dodgers retains one real calculated tie: Glasnow and Ohtani both have a median-to-median change of zero. No value or event was altered to break that tie.','','**Checks:** 25 eligible cards and 125 usable measurement windows; original prices unchanged. Runtime tests and production build pass. Existing dates and event sets are unchanged; only upcoming scoring was changed.','','**Scheduling approval remains pending.** Review these revised sets before authorizing their addition. The scoring approval did not authorize adding the proposed editions.','','[Exact scores and provenance](review/reviewed-proposal.json) · [Source audit](audit-other/REVIEW.md)']
(base/'APPROVAL-REVIEW.md').write_text('\n'.join(lines)+'\n')
(base/'scoring-change/REVIEW.md').write_text('# Exact-move scoring\n\nThe one-percentage-point tie tolerance has been removed for upcoming games and previews. Calculations remain unrounded; display uses one decimal place. Only mathematical equality, allowing Number.EPSILON × 4 of binary arithmetic noise, forms a tie.\n\nSee the [current five-day review](../APPROVAL-REVIEW.md). Trump, Thunder, Fed and NYC each have five distinct ranks. Dodgers has four, with Glasnow and Ohtani both at zero.\n\nExisting September7–10 scoring versions remain intact to preserve saved results. September11–12 and proposed editions use pairwise-exact-v3. No new schedule entries or deployment.\n')
