"""Compile a sourced candidate comparison from retained public market records."""
import datetime,json,pathlib
P=pathlib.Path(__file__).resolve().parent
def read(n):return json.loads((P/n).read_text())
cat=read('catalogue.json');broad={x['key']:x for x in read('broad-screen.json')};swings=read('pre-ending-swings.json')['candidates'];requests=read('history-requests.json')
notes={
 'tiktok':('Advance first','Everyday app, political rescue route, legal defeats and reversals. Five meaningful clusters span November–January; the disputed final YES is a memorable ending.','Strongest measured frozen set. Four tie groups and movements of both signs over 10 pp. First-public release/archive review remains.','Ban on download and/or use for most Americans effective by Apr30 2025 23:59 ET; federal mandate required; compliant sale NO. Federal-government evidence primary.','https://polymarket.com/event/tiktok-banned-in-the-us-before-may-2025'),
 'eagles':('Advance second','Super Bowl / Mahomes / Hurts / Barkley: mainstream stakes, a notorious loss, a record run, an injury, snow and a championship berth across a season.','Both signs, but early responses modest; two playoff responses tied. Final-whistle immutable records and independent review remain.','Philadelphia wins Super Bowl LIX; elimination allows early NO.','https://polymarket.com/event/superbowl-champion-2025/will-the-eagles-win-super-bowl-2025'),
 'trump':('Advance third','Verdict, shooting, rival endorsement, debate and surprise poll across six months. Exceptional recognition and a surprising negative endorsement response.','Strict windows pass, but three tie groups; shooting repeats a Biden #001 card. Source timing/ABC update review remains.','Trump wins presidency; AP, Fox and NBC agreement, else inauguration fallback Jan20 2025.','https://polymarket.com/event/presidential-election-winner-2024/will-donald-trump-win-the-2024-us-presidential-election'),
 'nyc':('Hold frozen set','New York establishment versus a young insurgent, with AOC, Cuomo, Hochul and Adams as familiar supporting characters.','Prices excellent; one +33.8 pp breakthrough overwhelms four small moves. Do not mine the pre-primary drawdown for a replacement headline after seeing scores.','Mamdani wins November4 GENERAL election; AP/Fox/NBC agreement else official certification.','https://polymarket.com/event/new-york-city-mayoral-election/will-zohran-mamdani-win-the-2025-nyc-mayoral-election'),
 'anora-poly':('Blocked alternate provider','Same 2025 Best Picture story as the Kalshi finalist; potentially cleaner recent hourly history.','Opened Jan21, after Jan5 Globes and under 84 hours before Jan23 nominations. Cannot supply the frozen arc or be stitched to Kalshi.','Best Picture winner; un-nominated films NO; no winner by Jun30 or tie uses alphabetically first nominated film. Academy/broadcast primary.','https://polymarket.com/event/oscars-best-picture/oscars-best-picture-will-anora-win-best-picture-at-the-2025-oscars'),
 'canada':('Closest fresh political alternative','A governing-party comeback around Trudeau’s exit, Carney’s arrival and conflict with Trump gives a months-long story and major reversals. Carney was sworn in March14, documented by the Canadian prime minister’s office.','2,723 hourly observations, no internal gaps. Needs a fresh significance-first five and timestamp audit. The market opens after Trudeau’s Jan6 resignation announcement, so that obvious opening headline cannot be scored with an 84-hour baseline. Recognition weaker outside Canada.','Liberal Party most House seats, not majority, popular vote or coalition; alphabetic tie-break; no vote by Dec31 NO; credible consensus then Elections Canada.','https://polymarket.com/event/which-party-wins-most-seats-in-canadian-election/will-the-liberal-party-win-the-most-seats-in-the-next-canadian-election'),
 'bitcoin':('Strong data; lower editorial fit','The $100,000 milestone is famous and offers ETF access, forced selling, an election and corporate buying across months.','Retained data are the YES prediction token, never BTC spot. Very large broad rise and fall. Existing draft has overlapping windows and specialist ETF/regulatory material; it has not earned priority merely by existing. A fresh five-card selection/timestamp review is required.','Coinbase BTC-USD one-minute candle final High reaches $100,000 within calendar2024 ET; specific discrepancy fallback to credible consensus.','https://polymarket.com/event/will-bitcoin-hit-100k-in-2024'),
 'gta':('Hold: obvious ending consumes main shock','Grand Theft Auto VI is exceptionally recognizable; a release-date guessing game could appeal beyond prediction-market specialists.','The 2025-release question is concluded and resolved NO even though the game itself was still unreleased at research time. Exclude the May2 official 2026-delay announcement from scoring as the natural resolving ending; pre-delay series still swings, but five independent factual pre-delay developments were not established. Do not use Take-Two stock or trailer speculation as substitute odds/evidence.','Official US public purchase/download release by Dec31 2025 23:59 ET, one console sufficient; betas, early access and leaks do not count; Rockstar/Take-Two primary.','https://polymarket.com/event/gta-vi-released-in-2025'),
 'taylor':('Hold: headline integrity','Taylor Swift and Travis Kelce are the strongest celebrity-recognition candidate. The engagement contract spans almost eight months with large movements in both directions.','Exact resolved contract and prices exist. Five distinct well-sourced developments genuinely bearing on engagement, rather than relationship gossip or repeated appearances, were not established. Engagement announcement is ending only; do not manufacture breakup rumors to get falling cards.','Announced engagement by Dec31 2025 23:59 ET; announced marriage also YES; couple/official representatives primary, credible consensus allowed.','https://polymarket.com/event/taylor-swift-and-travis-kelce-engaged-in-2025'),
 'fed':('Reject for launch entertainment','A real 25-versus-50-basis-point policy cliffhanger with economic releases and central-bank signals over weeks.','Data and primary releases are strong, but five inflation/jobs/speech cards are a dry fit for this mainstream launch request. Existing draft also has release-window overlap. Technical quality does not override entertainment priority.','September2024 meeting cuts upper target bound by at least50bp relative to prior level; FOMC statement source; absent statement by Nov6 resolves no-change bracket.','https://polymarket.com/event/fed-interest-rates-september-2024/fed-decreases-interest-rates-by-50-bps-after-september-2024-meeting'),
 'twitter':('Blocked: wrong contract horizon and empty history','Elon Musk buying Twitter is an outstanding mainstream business saga in principle.','This verified contract resolves on the April agreement announcement, not the October closing. It only spans roughly April14–25 and cannot cover the later withdrawal/lawsuit/closing saga. Every retained CLOB request returned an empty history. This does not prove no other Twitter contract or archive exists; it proves this one is unsuitable.','Twitter announces agreement to be acquired by Musk/entity by Jun1 2022 23:59:59 ET; completion unnecessary; later withdrawal does not undo YES.','https://polymarket.com/event/will-twitter-agree-to-a-musk-acquisition-by-june-1-2022'),
 'chiefs':('Alternate angle, not an extra independent story','Mahomes, Kelce and the attempted three-peat are compelling. Season-long title futures have real odds and a long runway.','Same Super Bowl story family as Eagles, not counted toward the 12 distinct storylines. The ultimate loss belongs in the ending; five prior game wins risk repetition and mechanical advancement. Eagles gives more varied setbacks and a quarterback-health episode.','Kansas City wins Super Bowl LIX; elimination allows early NO.','https://polymarket.com/event/superbowl-champion-2025/will-the-chiefs-win-super-bowl-2025')
}
order=['tiktok','eagles','trump','nyc','anora-kalshi','canada','bitcoin','oscars26','gta','taylor','twitter','fed','chiefs','anora-poly']
kalshi={
 'anora-kalshi':read('evidence/anora-kalshi-market.json')['market'],
 'oscars26':read('evidence/kalshi26.json')['market']
}
notes['anora-kalshi']=('Blocked despite strong story','Anora’s Globes shutout, nomination rivalry, guild comeback and Conclave challenges make a much more reversible awards story than five precursor wins.','1,718 missing hourly buckets; Globes anticipation coverage at most25% at every hourly alignment on Jan5 LA, below60%. Day-only source timing also unfinished. No five-card rank.','Anora wins Best Picture at97th Academy Awards, expected Mar2 2025.','https://api.elections.kalshi.com/trade-api/v2/historical/markets/KXOSCARPIC-25-A')
notes['oscars26']=('Closest data-accessible culture fallback','Leonardo DiCaprio’s One Battle After Another versus Sinners brings movie-star recognition and a completed Oscars race.','Fresh historical API retrieval succeeds. Existing draft review flags precursor redundancy, exact source cutoffs and result-as-ending work. Needs an independently selected five with rises AND falls before claiming a better puzzle than Anora; no fresh five-card scores run here.','One Battle After Another wins Best Picture at98th Academy Awards, expected Mar15 2026.','https://api.elections.kalshi.com/trade-api/v2/historical/markets/KXOSCARPIC-26-ONE')

lines=['# Candidate contract and data audit','', 'Research date: 2026-09-06. **12 distinct storylines**, plus a Chiefs alternate angle and an Anora alternate provider: **14 separately audited contracts/series**. No double-counting of those alternates toward the twelve. Rankings are editorial judgments, not a claim of exhaustive global search.','', 'Full Gamma descriptions, outcome tokens and resolution fields are in [catalogue.json](catalogue.json); Kalshi records are retained individually. All YES token IDs below come from provider outcome order, not article odds. Raw requests and receipt hashes are in [the retrieval ledger](history-requests.json) and [receipts](history-requests-receipts.json).','']
for n,key in enumerate(order,1):
    status,hook,verdict,rules,url=notes[key];a=broad.get(key,{})
    if key in cat:
        m=cat[key];id=m['id'];token=json.loads(m['clobTokenIds'])[0];q=m['question'];result='YES' if json.loads(m['outcomePrices'])[0]=='1' else 'NO';opened=m['startDate'];closed=m['closedTime'];meta=f'https://gamma-api.polymarket.com/markets/{id}';verified=f'`umaResolutionStatus={m.get("umaResolutionStatus")}`, `closed={m["closed"]}`, outcome prices `{m["outcomePrices"]}`'
    else:
        m=kalshi[key];id=token=m['ticker'];q=m['title'];result=m['result'].upper();opened=m['open_time'];closed=m['close_time'];meta=url;verified=f'`status={m["status"]}`, `result={m["result"]}`, `expiration_value={m["expiration_value"]}`, `settlement_ts={m["settlement_ts"]}`'
    req=[(k,u) for k,u in requests if k.startswith(key+'-history')]
    lines += [f'## {n}. {q}', '',f'**Decision:** {status}. **Resolved outcome:** {result}. **Provider ID:** `{id}`.','',f'**Market URL:** [market/official record]({url}). **Resolution evidence:** [provider metadata]({meta}), retained as {verified}. **Exact YES contract:** `{token}`.','',f'**Provider dates:** {opened} → {closed}.','',f'**Rules, summarized:** {rules}','',hook,'',verdict,'']
    if a.get('observations'):
        lines += [f'**Retrieved coverage:** {a["coverageStart"]} → {a["coverageEnd"]}; {a["observations"]:,} retained hourly buckets from {a["rawObservations"]:,} returned rows. {a["missingHours"]:,} internal missing buckets; maximum gap {a["maximumMissingRunHours"]} hours; {a["rejectedObservations"]} rejected rows. [Audit with gaps](evidence/{key}-audit.json).','']
        s=swings[key];up=s['maximumRise'];dn=s['maximumDrawdown']
        lines += [f'**Calculated broad pre-ending movements:** maximum chronological daily-median rise {up["pp"]:.2f} pp ({up["from"]["date"]}: {up["from"]["median"]*100:.3f}% → {up["to"]["date"]}: {up["to"]["median"]*100:.3f}%); drawdown {dn["pp"]:.2f} pp ({dn["from"]["date"]}: {dn["from"]["median"]*100:.3f}% → {dn["to"]["date"]}: {dn["to"]["median"]*100:.3f}%). At least12 actual samples/day; exclude {s["exclusiveEndingDateUTC"]} UTC onward. These are not headline scores.','']
    else:lines += ['**Retrieved coverage:** none. Exact contract verified, but retained historical responses contain zero points. No continuous data, frequency, liquidity or swings can be certified.','']
    if req:lines += [f'**Concrete retrieval:** [first exact request]({req[0][1]}), {len(req)} retained request(s); [full parameters and intervals](history-requests.json). No underlying stock/crypto series or other outcome contracts substituted.','']
    if key=='canada':lines += ['Primary story corroboration: [Canadian government, Carney swearing-in March14](https://www.pm.gc.ca/en/news/news-releases/2025/03/14/swearing-30th-canadian-ministry).','']
    if key=='gta':lines += ['Primary story corroboration: [Rockstar’s announcement of a May26 2026 release](https://www.rockstargames.com/newswire/article/258aa538o412ok/grand-theft-auto-vi-is-now-coming-may-26-2026). The later 2026 schedule is irrelevant to settlement of the 2025 contract.','']
    if key=='fed':lines += ['Primary ending corroboration: [Federal Reserve September18 statement](https://www.federalreserve.gov/newsevents/pressreleases/monetary20240918a.htm).','']
    if key=='oscars26':lines += ['Primary ending corroboration: [Academy’s own Best Picture presentation video](https://www.youtube.com/watch?v=bz1Uxlw1gu4). Existing review: [Oscars 2026](../editorial/oscars-2026-review.md).','']
(P/'candidate-audit.md').write_text('\n'.join(lines)+'\n')

report='''# NexusPoint: launch queue research

Research completed September 6, 2026. Scope: research and editorial preparation in this directory only.

## Recommendation

**Make TikTok, “The app that went dark,” the first choice for puzzle #002 once its remaining timestamp/evidence review clears.** It combines universal recognition, a months-long political/legal story, substantial measured rises and falls, a nearly motionless apparent lifeline, and a disputed-but-final ending. The provider explicitly records two disputed YES proposals followed by final YES. [Polymarket market and resolution record](https://polymarket.com/event/tiktok-banned-in-the-us-before-may-2025).

This research does **not** establish five queue-ready editions. It establishes **three strong candidates to advance**, a fourth with usable data but a weak frozen five-card arc, and a fifth blocked by historical gaps. **None can be queued now under the repository’s editorial requirements.** All four populated scoring sets still use some conservative public cutoffs awaiting first-public/immutable-source review; Anora fails a hard data requirement. Those distinctions are not hidden behind a generic “research complete” label.

Exactly five briefs are supplied in this proposed release-preference order. The last two positions are conditional research slots, not reservations or publication instructions. Do not schedule them merely to fill the queue.

| Preference | Edition / brief | Frozen scored range | What makes the ranking interesting | Readiness |
|---|---|---:|---|---|
| #002 | [The app that went dark](briefs/002-tiktok.md) | −11.75 to +12.50 pp | Two legal blows tie; review grant barely moves odds | Needs first-public court/brief/AP source confirmation and independent review |
| #003 | [Stop the three-peat](briefs/003-eagles.md) | −2.90 to +6.075 pp | Snow escape ties the 55-point conference win | Needs immutable final-whistle confirmation and independent review |
| #004 | [The comeback nobody could call](briefs/004-trump.md) | −3.45 to +10.00 pp | Kennedy endorsement measures negative; debate and Iowa poll tie | Needs broadcast/source-cutoff review; avoid immediate repetition after Biden |
| #005, hold | [The New York upset](briefs/005-nyc.md) | −1.025 to +33.80 pp | Big primary breakthrough versus mostly small later news | Data passes; frozen puzzle does not yet meet the strongest-story standard |
| #006, blocked | [Anora: Hollywood’s false finish](briefs/006-anora-kalshi.md) | No valid five-card ranking | Great fall/comeback/rival narrative | Exact ticker’s early history cannot support the required windows |

Ranges are newly calculated signed percentage-point responses using the unchanged project algorithm at the documented cutoffs. They are provisional research results, not causal effects or published answer keys. Ties use the project’s one-point anchor rule.

## What was reviewed first

The research started with the README, generalized Study schema, event-window implementation, source/provenance guidance, provider importers and current editorial records. Specifically: [README](../../README.md), [study schema](../../src/domain/study.ts), [measurement rules](../../src/domain/eventStudy.ts), [daily registry](../../src/data/dailyPuzzles.ts), [data provenance](../data-provenance.md), [generalized-study ADR](../adr/001-generalized-event-studies.md), [portfolio editorial review](../editorial/portfolio-review.md), [Biden review](../editorial/biden-dropout-2024-review.md), [Oscars review](../editorial/oscars-2026-review.md), the five existing topic definitions and the Polymarket/Kalshi importers. The existing daily registry supplied only the Biden edition, puzzle #001. Existing drafts were evidence to inspect, not presumptive winners.

The portfolio review requires an independent editor to confirm first-public timestamps, immutable source captures, event independence and mechanisms, then record reviewer identity and time before publication. This research supplies a reviewable packet; it does not invent an independent approval or ask to change publication state. The legacy election study does not exempt a new strict five-card daily edition from these requirements. [Existing sign-off requirement](../editorial/portfolio-review.md).

## Candidate screen: twelve distinct storylines

Twelve distinct storylines were researched through actual provider records and historical requests. A Chiefs version of the same Super Bowl and a second Anora provider were also tested, making **14 contract series**, without counting those alternates as additional independent stories. The [complete candidate audit](candidate-audit.md) supplies every exact question, ID/token, outcome, rules summary, dates, market link, retrieval path, gap count and numerical broad swing evidence.

| Storyline | Recognition / entertainment judgment | Data result | Editorial decision |
|---|---|---|---|
| TikTok US ban | Very high; app, president, courts, blackout | 3,023 hourly points; 1 gap | Strongest advance |
| Eagles Super Bowl season | Very high; star players, injury, snow, rivalry | 5,167 points; 2 gaps | Advance; two playoff cards tie |
| Trump wins 2024 presidency | Exceptional; five very different national moments | 4,549 points; 3 gaps | Advance after two varied editions |
| Mamdani NYC general election | High US political recognition | 4,711 points; 6 gaps | Hold frozen five: one dominant move |
| Anora Best Picture 2025 | Familiar ceremony; less familiar film; excellent reversal | Kalshi 1,392 points, 1,718 gaps | Blocked; alternate Polymarket opens too late |
| Canadian Liberal comeback 2025 | Strong Canada / Trump conflict story; less universal | 2,723 points; no gaps | Closest fresh political alternative; five-source freeze unfinished |
| Bitcoin reaches $100k in 2024 | Famous milestone; some specialist mechanisms | 6,609 prediction-odds points; 3 gaps | Strong alternative data; avoid specialist-heavy five |
| One Battle After Another Best Picture 2026 | Oscars + DiCaprio; more recent | 4,168 points; 21 gaps | Closest accessible culture fallback; precursor redundancy unresolved |
| GTA VI released in 2025 | Huge gaming recognition | 8,088 points; 8 gaps | Main delay is ending; five prior factual developments not established |
| Taylor Swift / Travis Kelce engagement 2025 | Exceptional celebrity recognition | 5,714 points; 1 gap | Five non-gossip developments not established |
| Musk–Twitter acquisition agreement 2022 | Exceptional business drama | Contract verified; zero returned prices | Wrong horizon for full saga; data blocked |
| September 2024 Fed 50+bp cut | Real suspense; dry for this audience | 1,129 points; no gaps | Reject launch priority on entertainment |

Chiefs alternate: 5,173 points, 2 gaps; title loss must remain in the ending and the prior wins are repetitive. Anora Polymarket alternate: 971 points, no gaps, but starts January 21 and cannot cover the January 5 Globes. These totals count actual retained UTC hourly buckets; gaps are internal to the observed span, not a blanket statement about full lifetime completeness. [Audits and exact source requests](candidate-audit.md).

The screen favors recognition, emotional stakes, variety of developments, a narrative that lasts weeks/months, and clear reversals. Data suitability is a pass/fail prerequisite for readiness. It does not award a dry contract a launch slot for having easy data, or a famous subject a ready label because a price chart appears in an article.

## Historical data: what is actually verified

**208 historical GET requests** were saved with exact URLs, returned bodies, retrieval times and SHA-256 hashes. They include successful empty results for the old Twitter contract. Provider metadata was retrieved independently of price history. [Request ledger](history-requests.json), [retrieval receipts](history-requests-receipts.json), [Gamma metadata catalogue](catalogue.json), [Kalshi Anora metadata](evidence/anora-kalshi-market.json), [Kalshi 2026 metadata](evidence/kalshi26.json).

Polymarket uses one precise YES outcome token per series and its public CLOB `prices-history` endpoint with Unix-second bounds and `fidelity=60`. Bounded requests cover each stated research range; overlapping boundary observations are resolved to the latest observation per UTC hour, matching the project convention. Prices outside [0,1] are rejected rather than clipped. Eagles, for example, has five invalid late rows; even its current consumer page shows a nonsensical 100.4% display, so the display is not used as a probability datum or settlement proof. Provider resolved status and outcome fields supply settlement evidence. [Eagles market](https://polymarket.com/event/superbowl-champion-2025/will-the-eagles-win-super-bowl-2025), [Eagles audit](evidence/eagles-audit.json).

CLOB price marks do not expose historical bid/ask spreads, depth, transaction-level volume or trade freshness. The importer calls them `trade` marks for compatibility; that does **not** establish that a trade occurred in every hour. Repeated timestamps counted as updates by the quality implementation must not be described as independent traders or price-changing trades. Lifetime market volume is not event-window liquidity. No provider’s promotional claim about market accuracy was accepted as research evidence.

Kalshi historical 60-minute candles use actual closing trades, or a closing bid/ask midpoint only within the project’s 20-point spread limit when no trade close exists. There is no previous-price carry, interpolation or cross-provider repair. Seven Anora candles lacked acceptable marks. Missing overnight/early intervals remain missing. The [Anora coverage envelope](anora-coverage-envelope.json) checks every hourly bucket alignment across the January 5 Los Angeles date: maximum anticipation coverage is **25%**, versus **60% required**. This is a coverage-only falsification, not a search for the best scoring timestamp.

All broad volatility numbers are **calculated from retained prediction probabilities**. [Pre-ending swings](pre-ending-swings.json) uses UTC daily medians with at least 12 actual hourly samples and excludes the whole resolving-announcement/result date onward. This corrects a common trap: GTA’s May delay cannot inflate its suitability as a scored headline just because formal settlement happened in January 2026. TikTok’s broad swing screen stops before the January 17 ruling. No scattered press odds are presented as continuous data. BTC spot price appears only in the Bitcoin contract’s resolution definition, never in its probability series.

The original [broad screen](broad-screen.json) is preserved as part of the audit trail; its mechanical last-three-days exclusion was an initial screen, not the final ending-aware measure. Prefer `pre-ending-swings.json` for reported suitability numbers. No new event scores were used to select the five facts per finalist.

## Selection integrity and measured findings

The [frozen selection](frozen-selection-v1.json) records the 25 event clusters, their significance and expected direction at **2026-09-06 00:24:51.987941 UTC**, before fresh event calculations. It candidly discloses that the required repository review exposed earlier measurements for some reused Trump/Eagles events and that broad prices had already been examined. This is a prospective frozen selection, not a claim of a blinded experiment.

[Anchor v1](anchors-v1.json) and [anchor v2](anchors-v2.json) were written before scoring. The only v2 change replaced a provisional Adams-post time with a directly retained contemporary NY1 reproduction cutoff, seven minutes later. No price response motivated the correction. The TikTok election card’s wording was narrowed to the election result because the earlier save-TikTok pledge lacked a retained contemporary primary source; the underlying frozen event cluster did not change. No weak card was exchanged after its score became visible.

The evaluation imports the project’s unchanged `calculateStudyImpacts`, `MONTHS_PROFILE` and `createTieGroups` directly. Primary score: stabilized median [18,36) hours minus reference median [−12,0), with separate anticipation [−84,−12), immediate [0,6), and delayed [48,72) quality checks. Every window must pass. Tie groups use a 1 pp distance from the group’s leading score. No causal attribution percentage is assigned. [Full reproducible results, profile and implementation hash](measurements-v1.json).

TikTok, Eagles, Trump and Mamdani each pass all 25 window checks at their documented cutoffs. The freeze nevertheless exposes editorial weaknesses: RFK’s seemingly helpful endorsement measures a fall; Mamdani’s other four cards barely move; Anora’s partial native calculations must not be treated as a valid five-card answer. The briefs preserve these outcomes. Anora’s day-end scenarios are explicitly hypothetical eligibility checks, with no asserted public minute or published ranking.

## Timing, hindsight and confounds

A headline’s importance is not identical to its first appearance, and a page’s original publication timestamp is not proof that its current full text existed then. Eagles live recaps were modified after publication; the DGA winner-page metadata appears earlier than the ceremony; the Golden Globes winners page was published January 7 although the event was January 5; the ABC debate transcript was updated after its original publication. These are material limitations recorded beside the affected cards, not silently corrected to convenient round hours.

The first four briefs use public upper bounds from live broadcast brackets/program endings, official oral-argument completion, indexed first-person posts, or retained publication/modification metadata. These support provisional measurement, while first-public access and immutable content still require editorial confirmation. Anora has day-only event evidence and no integration-ready exact times. Retained hashes prove the bytes retrieved now, not what an editable page showed in 2024/2025. Every packet leaves unresolved integration fields null instead of fabricating them.

No pair of separately scored events has overlapping full windows in these five frozen sets. There are still important within-event and unselected-news overlaps: games unfold before recap cutoffs; Eagles playoff weekends include other teams’ outcomes; the TikTok hearing is a long public process; election-night returns precede AP’s call; Kennedy’s endorsement follows the Democratic convention; the Iowa poll’s delayed window reaches early election-night information. The Anora guild weekend deliberately combines three linked awards into one card. Detailed anticipation and competing explanations accompany each of the 25 headlines.

Final results are never scored: the Super Bowl result, November presidential call for Trump, November NYC general result, TikTok January ruling/blackout/settlement and Anora’s Oscar are separate endings. The TikTok election result is allowable because it does not resolve the TikTok contract; similarly, the NYC primary concession does not resolve the general-election contract. This distinction follows the exact contract, not the emotional climax of an unrelated story.

## Closest alternatives and precise blockers

**Canadian Liberal comeback:** the best next fresh research lead if Mamdani stays on hold. The verified single Liberal-most-seats series rises from a 3.975% daily median on January 7 to 86% on April 24 and has a 10-point drawdown before the result. The price prerequisite is satisfied. The remaining work is a separately frozen five-event timeline with primary public times and balanced developments. Trudeau’s resignation cannot be used with this market’s opening. Carney’s actual March14 swearing-in is independently documented. [Provider contract](https://gamma-api.polymarket.com/markets/517586), [Canadian government record](https://www.pm.gc.ca/en/news/news-releases/2025/03/14/swearing-30th-canadian-ministry).

**One Battle After Another, Oscars 2026:** the best accessible cultural fallback for Anora. Its verified Kalshi ticker has 4,168 retained hourly marks and only 21 isolated missing buckets. The issue is five distinct, entertaining pre-result developments instead of a procession of precursor wins, plus the remaining source/timestamp requirements already identified in the repository review. No new five-card selection has been frozen or scored here, so it is not falsely labeled ready. [Provider contract](https://api.elections.kalshi.com/trade-api/v2/historical/markets/KXOSCARPIC-26-ONE), [existing editorial record](../editorial/oscars-2026-review.md).

**Bitcoin $100k:** strong actual odds and huge two-way movement make it a viable reserve if the audience is comfortable with business/technology. The blocker is a fresh mainstream five with clean timing/overlap review; the existing draft contains specialist material and does not get automatic priority. **Swift/Kelce** and **GTA** have verified resolved contracts and prices but do not yet have five sufficiently independent, factual, pre-ending developments. **Musk/Twitter** needs an entirely different, demonstrably retrievable completion contract to tell the full takeover saga. [All exact contracts and evidence](candidate-audit.md).

## Deliverables and handoff

Each of the five briefs includes a punchy title, exact contract and outcome, story dates, audience/game rationale, full price retrieval path and coverage, five frozen headlines with public evidence, measured or explicitly ineligible windows, confounds, a separate ending and precise readiness gates. Beside each Markdown brief is a structured JSON handoff with stable event IDs, YES orientation, source hashes, request intervals, presentation draft, fixed initial card order and research-only dataset references. Five native-format hourly CSVs are under `datasets/`.

The packets are ready to hand to an integrator/editor; they are **not five approved, drop-in Study objects**. Final occurrence timestamps and source roles/publication records require the identified evidence work, and no independent reviewer identity or approval time is invented. No release date is assigned. No application code, publication status, daily registry or deployment was changed by this research. Concurrent changes outside this directory were left untouched.

**Queue now: zero. Advance next: TikTok, Eagles, Trump. Hold: Mamdani. Blocked: Anora.** Do not lower the bar to fill the last two slots.
'''
(P/'research-report.md').write_text(report)
print('Wrote research-report.md and candidate-audit.md.')
